name: Check Version

on:
  push:
    branches:
      - master

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Validate Version
      shell: bash
      run: |
        VERSION_FILE_PATH='pytest_compare/__init__.py'
        VERSION_REGEX='^(__version__ = \"(\d+.)*)(\d+)((a|b|rc)\d*)?(.post\d+)?(.dev\d+)?(\")$'
        
        if grep -Eo "$VERSION_REGEX" $VERSION_FILE_PATH
        then
          echo "Version is in a correct format"
        else
          echo "No correct version found in $VERSION_FILE_PATH"
        exit 1
        fi
