name: Release Version

on:
  release:
    types: [published]

jobs:
  release_package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install python dependencies
      run: pip install --upgrade pip setuptools wheel build twine

    - name: Increment Version
      shell: bash
      run: |
        VERSION_FILE_PATH='pytest_compare/__init__.py'
        VERSION_REGEX='^((__version__ = \"([[:digit:]]+.)*)([[:digit:]]+)((a|b|rc)[[:digit:]]*)?(.post[[:digit:]]+)?(.dev[[:digit:]]+)?(\"))$'
        
        NEW_MINOR=`sed -En "s/$VERSION_REGEX/\4/p" $VERSION_FILE_PATH | awk '{print $1 + 1}'`
        sed -Ei "s/$VERSION_REGEX/\2$NEW_MINOR\9/" ${{ inputs.version_file_path }}
        
        RELEASE_VERSION=`sed -En "s/$VERSION_REGEX/\1/p" $VERSION_FILE_PATH`
        echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
        echo "Created version $RELEASE_VERSION"

    - name: Commit Changes
      shell: bash
      run: |
        git config --local user.name "Python Release"
        git config --local user.email "action@github.com"
        git commit -a -m "${{ env.RELEASE_VERSION }} - [skip actions]"
        git push

    - name: Build and Publish
      shell: bash
      run: |
        python -m build
        twine upload dist/* --verbose

    - name: Release New Version
      uses: softprops/action-gh-release@v1
      with:
        name: v${{ env.RELEASE_VERSION }}
        tag_name: v${{ env.RELEASE_VERSION }}
