name: Release Version

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - shell: bash
      run: |
        VERSION_REGEX = ^(__version__ = "(\d+.)*)(\d+)((a|b|rc)\d*)(.post\d+)?(.dev\d+)?(")
