name: Tests

on: push

jobs:
  test:
    runs-on: lmnd-runners
    steps:
    - uses: actions/checkout@v3

    - id: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -e ."[pandas]"

    - name: Run black formatter
      uses: psf/black@stable
      with:
        options: "--check"

    - name: Run tests
      run: pytest
